// Generated by setup-api-keys.js
// This file contains front-end accessible configuration

const config = {
  useMockServer: false,
  apiBaseUrl: 'http://localhost:3001',
  hasHunterApiKey: true,
  hasCrunchbaseApiKey: false,
  hasGoogleApiKeys: false,
  googleClientId: '',
  googleApiKey: 'AIzaSyCl2W7vFyzFKYplBer50-4TnUSMsydXXg0',
};

export default config;