services:
  - type: web
    name: sales-meeting-ai
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node start-real-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_OPENAI_API_KEY
        sync: false
      - key: VITE_BUILTWITH_API_KEY
        sync: false
      - key: VITE_NEWSAPI_KEY
        sync: false 